/**
 * A curated list of well-known disposable/temp-email domains.
 * This is NOT exhaustive — new disposable email services appear constantly,
 * and this list can't keep up with all of them. It blocks the common,
 * well-established ones. For more complete coverage over time, consider
 * swapping this for a maintained API (e.g. Kickbox, ZeroBounce) once you
 * have a key to use — this list is a reasonable, zero-cost starting point.
 */
export const DISPOSABLE_EMAIL_DOMAINS = new Set([
  "mailinator.com",
  "guerrillamail.com",
  "guerrillamail.info",
  "guerrillamail.biz",
  "guerrillamail.de",
  "guerrillamailblock.com",
  "10minutemail.com",
  "10minutemail.net",
  "tempmail.com",
  "temp-mail.org",
  "temp-mail.io",
  "throwawaymail.com",
  "yopmail.com",
  "yopmail.fr",
  "yopmail.net",
  "sharklasers.com",
  "trashmail.com",
  "trashmail.net",
  "getnada.com",
  "fakeinbox.com",
  "dispostable.com",
  "mailnesia.com",
  "mytemp.email",
  "moakt.com",
  "emailondeck.com",
  "spamgourmet.com",
  "mintemail.com",
  "mohmal.com",
  "tempinbox.com",
  "maildrop.cc",
  "harakirimail.com",
  "mailcatch.com",
  "tempr.email",
  "discard.email",
  "discardmail.com",
  "mailsac.com",
  "inboxbear.com",
  "luxusmail.org",
  "burnermail.io",
  "mailpoof.com",
  "tempmailo.com",
  "tempmail.net",
  "tempmailaddress.com",
  "fakemail.net",
  "fakemailgenerator.com",
  "crazymailing.com",
  "spam4.me",
  "0-mail.com",
  "anonbox.net",
  "mailbox52.ml",
  "mailbox92.biz",
  "mailbox72.biz",
  "spambog.com",
  "spamfree24.org",
  "email-fake.com",
  "emailfake.com",
  "airmail.cc",
  "armyspy.com",
  "cuvox.de",
  "dayrep.com",
  "einrot.com",
  "fleckens.hu",
  "gustr.com",
  "jourrapide.com",
  "rhyta.com",
  "superrito.com",
  "teleworm.us",
]);

export function isDisposableEmail(email: string): boolean {
  const domain = email.split("@")[1]?.toLowerCase().trim();
  if (!domain) return false;
  return DISPOSABLE_EMAIL_DOMAINS.has(domain);
}
